In [3]:
import torch
import torch.nn as nn
import numpy as np
#inputs

inputs=torch.tensor(
    [1.0,2.0,3.0]
)

neuron=nn.Linear(
    in_features=3,
    out_features=1
)

output=neuron(inputs)
print(output)

print(neuron.weight)
print(neuron.bias)

print(neuron.weight @ inputs + neuron.bias)

tensor([-1.4071], grad_fn=<ViewBackward0>)
Parameter containing:
tensor([[-0.4464,  0.1874, -0.5007]], requires_grad=True)
Parameter containing:
tensor([0.1664], requires_grad=True)
tensor([-1.4071], grad_fn=<AddBackward0>)
